### ISSUE TITLE
How many servers are you running?

### ISSUE THREAD

**Issue by mkotsollaris** [brokenloop/Eliquid_mixer#1]
@brokenloop I have a twofold question:

- how many servers are in your application?
- If there are more that one server, can we decrease the amount?

**Comment by brokenloop** [comment]
There is currently one python flask server running for this application, but there is some dead code from an express server I played around with briefly. I should purge anything that isn't being used in this application.

**Comment by mkotsollaris** [comment]
I think I counted 4: `server.py`, `server.js` (in the root), `backend/server.py`, and 1 inside the client which boots up on `npm start`.

**Comment by brokenloop** [comment]
The version you were looking at was an old commit, updated now.

**Comment by mkotsollaris** [comment]
👍
